services:

  click-house:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8124:8123"
      - "8000:9000"
    volumes:
      - ./click/init:/docker-entrypoint-initdb.d
      - ./click/config.xml:/etc/clickhouse-server/config.xml
      - ./click/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    restart: on-failure

volumes:
  clickhouse_data:
  oracle_db_data:
  postgres_data: