version: '3.5'

services:
  registry:
    image: registry:2
    ports:
    - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./auth:/auth
      - /DOCKER_DATA/registry:/data
    networks:
      self:
          ipv4_address: 172.72.48.3

  docker-registry-ui:
     container_name: docker-registry-ui
     image: konradkleine/docker-registry-frontend:v2
     ports:
      - 8383:80
     environment:
       ENV_DOCKER_REGISTRY_HOST: myregistry.com 
       ENV_DOCKER_REGISTRY_PORT: 5000
     extra_hosts:
       - "myregistry.com:172.72.48.3"
     networks:
       self:
          ipv4_address: 172.72.48.4

networks:
  self:
    driver: bridge
    ipam:
     config:
       - subnet: 172.72.48.0/24

