version: '3.7'

services:
  sentry-redis:
    image: redis:7.2.4
    container_name: sentry-redis
    hostname: sentry-redis
    restart: always
    networks:
      - sentry
    volumes:
      - 'sentry_redis:/data'
  
  sentry-postgres:
    image: postgres:16
    container_name: sentry-postgres
    hostname: sentry-postgres
    restart: always
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: 89PsZXyRStOT2
      POSTGRES_DB: sentry
    networks:
      - sentry
    volumes:
      - 'sentry_postgres:/var/lib/postgresql/data'

  sentry-base:
    image: sentry:9.1.2
    container_name: sentry-base
    hostname: sentry-base
    restart: always
    ports:
      - '9000:9000'
    env_file:
      - .env
    depends_on:
      - sentry-redis
      - sentry-postgres
    networks:
      - sentry
    volumes:
      - 'sentry_data:/var/lib/sentry/files'

  sentry-cron:
    image: sentry:9.1.2
    container_name: sentry-cron
    hostname: sentry-cron
    restart: always
    env_file:
      - .env
    depends_on:
      - sentry-redis
      - sentry-postgres
    command: "sentry run cron"
    networks:
      - sentry
    volumes:
      - 'sentry_data:/var/lib/sentry/files'

  sentry-worker:
    image: sentry:9.1.2
    container_name: sentry-worker
    hostname: sentry-worker
    restart: always
    env_file:
      - .env
    depends_on:
      - sentry-redis
      - sentry-postgres
    command: "sentry run worker"
    networks:
      - sentry
    volumes:
      - 'sentry_data:/var/lib/sentry/files'

networks:
  sentry:
    driver: bridge

volumes:
  sentry_data:
  sentry_postgres:
  sentry_redis: